artifact_location: /Users/ipek/Downloads/AI-Powered-Object-Detection-Image-Captioning-Web-App-1/runs/mlflow/275437460596426797
creation_time: 1767097468705
experiment_id: '275437460596426797'
last_update_time: 1767097468705
lifecycle_stage: active
name: /Shared/Ultralytics
