artifact_location: /Users/ipek/Downloads/AI-Powered-Object-Detection-Image-Captioning-Web-App-1/runs/mlflow/0
creation_time: 1767097468701
experiment_id: '0'
last_update_time: 1767097468701
lifecycle_stage: active
name: Default
